android:
  gradle_root: content-rating-display-213568/vod_content_rating_frontend
  modules:
    - content-rating-display-213568/vod_content_rating_frontend/app
    - content-rating-display-213568/vod_content_rating_frontend/list
    - content-rating-display-213568/vod_content_rating_frontend/utilities
