.PHONY: android-root

ANDROID_ROOT=content-rating-display-213568/vod_content_rating_frontend

android-root:
	@echo "Android workspace: $(ANDROID_ROOT)"
	@echo "Wrapper: $(ANDROID_ROOT)/gradlew"
	cd $(ANDROID_ROOT) && ./gradlew :app:assembleDebug
